CREATE TABLE IF NOT EXISTS memos (
   id            INT          NOT NULL AUTO_INCREMENT,
   title         VARCHAR(256) NOT NULL,
   content       LONGTEXT     NOT NULL,
   created_date  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
   updated_date  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
   PRIMARY KEY (id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;